//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2.srv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        private bool ConnectedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Connected {
            get {
                return this.ConnectedField;
            }
            set {
                if ((this.ConnectedField.Equals(value) != true)) {
                    this.ConnectedField = value;
                    this.RaisePropertyChanged("Connected");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime TimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        private int Id_userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Msg {
            get {
                return this.MsgField;
            }
            set {
                if ((object.ReferenceEquals(this.MsgField, value) != true)) {
                    this.MsgField = value;
                    this.RaisePropertyChanged("Msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Id_user {
            get {
                return this.Id_userField;
            }
            set {
                if ((this.Id_userField.Equals(value) != true)) {
                    this.Id_userField = value;
                    this.RaisePropertyChanged("Id_user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srv.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsApp2.srv.HelloWorldResponse HelloWorld(WindowsFormsApp2.srv.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.srv.HelloWorldResponse> HelloWorldAsync(WindowsFormsApp2.srv.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name usname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Participer", ReplyAction="*")]
        WindowsFormsApp2.srv.ParticiperResponse Participer(WindowsFormsApp2.srv.ParticiperRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Participer", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.srv.ParticiperResponse> ParticiperAsync(WindowsFormsApp2.srv.ParticiperRequest request);
        
        // CODEGEN: Generating message contract since element name getparticipantsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getparticipants", ReplyAction="*")]
        WindowsFormsApp2.srv.getparticipantsResponse getparticipants(WindowsFormsApp2.srv.getparticipantsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getparticipants", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.srv.getparticipantsResponse> getparticipantsAsync(WindowsFormsApp2.srv.getparticipantsRequest request);
        
        // CODEGEN: Generating message contract since element name getmessagesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getmessages", ReplyAction="*")]
        WindowsFormsApp2.srv.getmessagesResponse getmessages(WindowsFormsApp2.srv.getmessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getmessages", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.srv.getmessagesResponse> getmessagesAsync(WindowsFormsApp2.srv.getmessagesRequest request);
        
        // CODEGEN: Generating message contract since element name getuserbyidResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getuserbyid", ReplyAction="*")]
        WindowsFormsApp2.srv.getuserbyidResponse getuserbyid(WindowsFormsApp2.srv.getuserbyidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getuserbyid", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.srv.getuserbyidResponse> getuserbyidAsync(WindowsFormsApp2.srv.getuserbyidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/quitter", ReplyAction="*")]
        void quitter(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/quitter", ReplyAction="*")]
        System.Threading.Tasks.Task quitterAsync(int id);
        
        // CODEGEN: Generating message contract since element name messagesbetweentwodatesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/messagesbetweentwodates", ReplyAction="*")]
        WindowsFormsApp2.srv.messagesbetweentwodatesResponse messagesbetweentwodates(WindowsFormsApp2.srv.messagesbetweentwodatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/messagesbetweentwodates", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.srv.messagesbetweentwodatesResponse> messagesbetweentwodatesAsync(WindowsFormsApp2.srv.messagesbetweentwodatesRequest request);
        
        // CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addmessage", ReplyAction="*")]
        WindowsFormsApp2.srv.addmessageResponse addmessage(WindowsFormsApp2.srv.addmessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addmessage", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp2.srv.addmessageResponse> addmessageAsync(WindowsFormsApp2.srv.addmessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.srv.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsApp2.srv.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.srv.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsApp2.srv.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParticiperRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Participer", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.srv.ParticiperRequestBody Body;
        
        public ParticiperRequest() {
        }
        
        public ParticiperRequest(WindowsFormsApp2.srv.ParticiperRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParticiperRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usname;
        
        public ParticiperRequestBody() {
        }
        
        public ParticiperRequestBody(string usname) {
            this.usname = usname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ParticiperResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ParticiperResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.srv.ParticiperResponseBody Body;
        
        public ParticiperResponse() {
        }
        
        public ParticiperResponse(WindowsFormsApp2.srv.ParticiperResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ParticiperResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp2.srv.User ParticiperResult;
        
        public ParticiperResponseBody() {
        }
        
        public ParticiperResponseBody(WindowsFormsApp2.srv.User ParticiperResult) {
            this.ParticiperResult = ParticiperResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getparticipantsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getparticipants", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.srv.getparticipantsRequestBody Body;
        
        public getparticipantsRequest() {
        }
        
        public getparticipantsRequest(WindowsFormsApp2.srv.getparticipantsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getparticipantsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getparticipantsRequestBody() {
        }
        
        public getparticipantsRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getparticipantsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getparticipantsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.srv.getparticipantsResponseBody Body;
        
        public getparticipantsResponse() {
        }
        
        public getparticipantsResponse(WindowsFormsApp2.srv.getparticipantsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getparticipantsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp2.srv.User[] getparticipantsResult;
        
        public getparticipantsResponseBody() {
        }
        
        public getparticipantsResponseBody(WindowsFormsApp2.srv.User[] getparticipantsResult) {
            this.getparticipantsResult = getparticipantsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getmessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getmessages", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.srv.getmessagesRequestBody Body;
        
        public getmessagesRequest() {
        }
        
        public getmessagesRequest(WindowsFormsApp2.srv.getmessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getmessagesRequestBody {
        
        public getmessagesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getmessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getmessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.srv.getmessagesResponseBody Body;
        
        public getmessagesResponse() {
        }
        
        public getmessagesResponse(WindowsFormsApp2.srv.getmessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getmessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp2.srv.Message[] getmessagesResult;
        
        public getmessagesResponseBody() {
        }
        
        public getmessagesResponseBody(WindowsFormsApp2.srv.Message[] getmessagesResult) {
            this.getmessagesResult = getmessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getuserbyidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getuserbyid", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.srv.getuserbyidRequestBody Body;
        
        public getuserbyidRequest() {
        }
        
        public getuserbyidRequest(WindowsFormsApp2.srv.getuserbyidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getuserbyidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public getuserbyidRequestBody() {
        }
        
        public getuserbyidRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getuserbyidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getuserbyidResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.srv.getuserbyidResponseBody Body;
        
        public getuserbyidResponse() {
        }
        
        public getuserbyidResponse(WindowsFormsApp2.srv.getuserbyidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getuserbyidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp2.srv.User getuserbyidResult;
        
        public getuserbyidResponseBody() {
        }
        
        public getuserbyidResponseBody(WindowsFormsApp2.srv.User getuserbyidResult) {
            this.getuserbyidResult = getuserbyidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class messagesbetweentwodatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="messagesbetweentwodates", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.srv.messagesbetweentwodatesRequestBody Body;
        
        public messagesbetweentwodatesRequest() {
        }
        
        public messagesbetweentwodatesRequest(WindowsFormsApp2.srv.messagesbetweentwodatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class messagesbetweentwodatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime d;
        
        public messagesbetweentwodatesRequestBody() {
        }
        
        public messagesbetweentwodatesRequestBody(int id, System.DateTime d) {
            this.id = id;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class messagesbetweentwodatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="messagesbetweentwodatesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.srv.messagesbetweentwodatesResponseBody Body;
        
        public messagesbetweentwodatesResponse() {
        }
        
        public messagesbetweentwodatesResponse(WindowsFormsApp2.srv.messagesbetweentwodatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class messagesbetweentwodatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApp2.srv.Message[] messagesbetweentwodatesResult;
        
        public messagesbetweentwodatesResponseBody() {
        }
        
        public messagesbetweentwodatesResponseBody(WindowsFormsApp2.srv.Message[] messagesbetweentwodatesResult) {
            this.messagesbetweentwodatesResult = messagesbetweentwodatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addmessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addmessage", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.srv.addmessageRequestBody Body;
        
        public addmessageRequest() {
        }
        
        public addmessageRequest(WindowsFormsApp2.srv.addmessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addmessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime d;
        
        public addmessageRequestBody() {
        }
        
        public addmessageRequestBody(string text, int id, System.DateTime d) {
            this.text = text;
            this.id = id;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addmessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addmessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp2.srv.addmessageResponseBody Body;
        
        public addmessageResponse() {
        }
        
        public addmessageResponse(WindowsFormsApp2.srv.addmessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class addmessageResponseBody {
        
        public addmessageResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WindowsFormsApp2.srv.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApp2.srv.WebService1Soap>, WindowsFormsApp2.srv.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.srv.HelloWorldResponse WindowsFormsApp2.srv.WebService1Soap.HelloWorld(WindowsFormsApp2.srv.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsApp2.srv.HelloWorldRequest inValue = new WindowsFormsApp2.srv.HelloWorldRequest();
            inValue.Body = new WindowsFormsApp2.srv.HelloWorldRequestBody();
            WindowsFormsApp2.srv.HelloWorldResponse retVal = ((WindowsFormsApp2.srv.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.srv.HelloWorldResponse> WindowsFormsApp2.srv.WebService1Soap.HelloWorldAsync(WindowsFormsApp2.srv.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.srv.HelloWorldResponse> HelloWorldAsync() {
            WindowsFormsApp2.srv.HelloWorldRequest inValue = new WindowsFormsApp2.srv.HelloWorldRequest();
            inValue.Body = new WindowsFormsApp2.srv.HelloWorldRequestBody();
            return ((WindowsFormsApp2.srv.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.srv.ParticiperResponse WindowsFormsApp2.srv.WebService1Soap.Participer(WindowsFormsApp2.srv.ParticiperRequest request) {
            return base.Channel.Participer(request);
        }
        
        public WindowsFormsApp2.srv.User Participer(string usname) {
            WindowsFormsApp2.srv.ParticiperRequest inValue = new WindowsFormsApp2.srv.ParticiperRequest();
            inValue.Body = new WindowsFormsApp2.srv.ParticiperRequestBody();
            inValue.Body.usname = usname;
            WindowsFormsApp2.srv.ParticiperResponse retVal = ((WindowsFormsApp2.srv.WebService1Soap)(this)).Participer(inValue);
            return retVal.Body.ParticiperResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.srv.ParticiperResponse> WindowsFormsApp2.srv.WebService1Soap.ParticiperAsync(WindowsFormsApp2.srv.ParticiperRequest request) {
            return base.Channel.ParticiperAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.srv.ParticiperResponse> ParticiperAsync(string usname) {
            WindowsFormsApp2.srv.ParticiperRequest inValue = new WindowsFormsApp2.srv.ParticiperRequest();
            inValue.Body = new WindowsFormsApp2.srv.ParticiperRequestBody();
            inValue.Body.usname = usname;
            return ((WindowsFormsApp2.srv.WebService1Soap)(this)).ParticiperAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.srv.getparticipantsResponse WindowsFormsApp2.srv.WebService1Soap.getparticipants(WindowsFormsApp2.srv.getparticipantsRequest request) {
            return base.Channel.getparticipants(request);
        }
        
        public WindowsFormsApp2.srv.User[] getparticipants(int id) {
            WindowsFormsApp2.srv.getparticipantsRequest inValue = new WindowsFormsApp2.srv.getparticipantsRequest();
            inValue.Body = new WindowsFormsApp2.srv.getparticipantsRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp2.srv.getparticipantsResponse retVal = ((WindowsFormsApp2.srv.WebService1Soap)(this)).getparticipants(inValue);
            return retVal.Body.getparticipantsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.srv.getparticipantsResponse> WindowsFormsApp2.srv.WebService1Soap.getparticipantsAsync(WindowsFormsApp2.srv.getparticipantsRequest request) {
            return base.Channel.getparticipantsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.srv.getparticipantsResponse> getparticipantsAsync(int id) {
            WindowsFormsApp2.srv.getparticipantsRequest inValue = new WindowsFormsApp2.srv.getparticipantsRequest();
            inValue.Body = new WindowsFormsApp2.srv.getparticipantsRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp2.srv.WebService1Soap)(this)).getparticipantsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.srv.getmessagesResponse WindowsFormsApp2.srv.WebService1Soap.getmessages(WindowsFormsApp2.srv.getmessagesRequest request) {
            return base.Channel.getmessages(request);
        }
        
        public WindowsFormsApp2.srv.Message[] getmessages() {
            WindowsFormsApp2.srv.getmessagesRequest inValue = new WindowsFormsApp2.srv.getmessagesRequest();
            inValue.Body = new WindowsFormsApp2.srv.getmessagesRequestBody();
            WindowsFormsApp2.srv.getmessagesResponse retVal = ((WindowsFormsApp2.srv.WebService1Soap)(this)).getmessages(inValue);
            return retVal.Body.getmessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.srv.getmessagesResponse> WindowsFormsApp2.srv.WebService1Soap.getmessagesAsync(WindowsFormsApp2.srv.getmessagesRequest request) {
            return base.Channel.getmessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.srv.getmessagesResponse> getmessagesAsync() {
            WindowsFormsApp2.srv.getmessagesRequest inValue = new WindowsFormsApp2.srv.getmessagesRequest();
            inValue.Body = new WindowsFormsApp2.srv.getmessagesRequestBody();
            return ((WindowsFormsApp2.srv.WebService1Soap)(this)).getmessagesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.srv.getuserbyidResponse WindowsFormsApp2.srv.WebService1Soap.getuserbyid(WindowsFormsApp2.srv.getuserbyidRequest request) {
            return base.Channel.getuserbyid(request);
        }
        
        public WindowsFormsApp2.srv.User getuserbyid(int id) {
            WindowsFormsApp2.srv.getuserbyidRequest inValue = new WindowsFormsApp2.srv.getuserbyidRequest();
            inValue.Body = new WindowsFormsApp2.srv.getuserbyidRequestBody();
            inValue.Body.id = id;
            WindowsFormsApp2.srv.getuserbyidResponse retVal = ((WindowsFormsApp2.srv.WebService1Soap)(this)).getuserbyid(inValue);
            return retVal.Body.getuserbyidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.srv.getuserbyidResponse> WindowsFormsApp2.srv.WebService1Soap.getuserbyidAsync(WindowsFormsApp2.srv.getuserbyidRequest request) {
            return base.Channel.getuserbyidAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.srv.getuserbyidResponse> getuserbyidAsync(int id) {
            WindowsFormsApp2.srv.getuserbyidRequest inValue = new WindowsFormsApp2.srv.getuserbyidRequest();
            inValue.Body = new WindowsFormsApp2.srv.getuserbyidRequestBody();
            inValue.Body.id = id;
            return ((WindowsFormsApp2.srv.WebService1Soap)(this)).getuserbyidAsync(inValue);
        }
        
        public void quitter(int id) {
            base.Channel.quitter(id);
        }
        
        public System.Threading.Tasks.Task quitterAsync(int id) {
            return base.Channel.quitterAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.srv.messagesbetweentwodatesResponse WindowsFormsApp2.srv.WebService1Soap.messagesbetweentwodates(WindowsFormsApp2.srv.messagesbetweentwodatesRequest request) {
            return base.Channel.messagesbetweentwodates(request);
        }
        
        public WindowsFormsApp2.srv.Message[] messagesbetweentwodates(int id, System.DateTime d) {
            WindowsFormsApp2.srv.messagesbetweentwodatesRequest inValue = new WindowsFormsApp2.srv.messagesbetweentwodatesRequest();
            inValue.Body = new WindowsFormsApp2.srv.messagesbetweentwodatesRequestBody();
            inValue.Body.id = id;
            inValue.Body.d = d;
            WindowsFormsApp2.srv.messagesbetweentwodatesResponse retVal = ((WindowsFormsApp2.srv.WebService1Soap)(this)).messagesbetweentwodates(inValue);
            return retVal.Body.messagesbetweentwodatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.srv.messagesbetweentwodatesResponse> WindowsFormsApp2.srv.WebService1Soap.messagesbetweentwodatesAsync(WindowsFormsApp2.srv.messagesbetweentwodatesRequest request) {
            return base.Channel.messagesbetweentwodatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.srv.messagesbetweentwodatesResponse> messagesbetweentwodatesAsync(int id, System.DateTime d) {
            WindowsFormsApp2.srv.messagesbetweentwodatesRequest inValue = new WindowsFormsApp2.srv.messagesbetweentwodatesRequest();
            inValue.Body = new WindowsFormsApp2.srv.messagesbetweentwodatesRequestBody();
            inValue.Body.id = id;
            inValue.Body.d = d;
            return ((WindowsFormsApp2.srv.WebService1Soap)(this)).messagesbetweentwodatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp2.srv.addmessageResponse WindowsFormsApp2.srv.WebService1Soap.addmessage(WindowsFormsApp2.srv.addmessageRequest request) {
            return base.Channel.addmessage(request);
        }
        
        public void addmessage(string text, int id, System.DateTime d) {
            WindowsFormsApp2.srv.addmessageRequest inValue = new WindowsFormsApp2.srv.addmessageRequest();
            inValue.Body = new WindowsFormsApp2.srv.addmessageRequestBody();
            inValue.Body.text = text;
            inValue.Body.id = id;
            inValue.Body.d = d;
            WindowsFormsApp2.srv.addmessageResponse retVal = ((WindowsFormsApp2.srv.WebService1Soap)(this)).addmessage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp2.srv.addmessageResponse> WindowsFormsApp2.srv.WebService1Soap.addmessageAsync(WindowsFormsApp2.srv.addmessageRequest request) {
            return base.Channel.addmessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp2.srv.addmessageResponse> addmessageAsync(string text, int id, System.DateTime d) {
            WindowsFormsApp2.srv.addmessageRequest inValue = new WindowsFormsApp2.srv.addmessageRequest();
            inValue.Body = new WindowsFormsApp2.srv.addmessageRequestBody();
            inValue.Body.text = text;
            inValue.Body.id = id;
            inValue.Body.d = d;
            return ((WindowsFormsApp2.srv.WebService1Soap)(this)).addmessageAsync(inValue);
        }
    }
}
